// Generated by npm run generate:presets. Do not edit by hand.
import type { DefaultOptimisationPreset } from "./defaultOptimisationPresets";

export const GENERATED_DEFAULT_OPTIMISATION_PRESET_MODEL_VERSION = "v4-discrete-products-exhaustive-2026-08-11-short-cashback-routing-4";
export const GENERATED_DEFAULT_OPTIMISATION_PRESETS: DefaultOptimisationPreset[] = [
  {
    "comparisonMode": "base",
    "objective": "bullish",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 10000,
        "longAllocation": 0.5,
        "longMode": "2.5x-looped",
        "shortMode": "2.5x-cashback",
        "shortLtv": 0.75,
        "longLtv": 0.75,
        "cashbackMode": "spot",
        "cashOutEnabled": true,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": null,
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 900,
            "regionsAvailable": 1818,
            "regionsRetained": 918,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 900,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": {
      "targetPercent": 200,
      "selected": {
        "config": {
          "deposit": 10000,
          "longAllocation": 0.5,
          "longMode": "2.5x-looped",
          "shortMode": "2.5x-cashback",
          "shortLtv": 0.75,
          "longLtv": 0.75,
          "cashbackMode": "spot",
          "cashOutEnabled": true,
          "degenEnabled": false,
          "degenMode": "x1",
          "customRecyclePct": 0
        },
        "routing": "spot",
        "targetReturn": 458.33333333333337
      },
      "alternative": {
        "config": {
          "deposit": 10000,
          "longAllocation": 0.5,
          "longMode": "2.5x-looped",
          "shortMode": "2.5x-cashback",
          "shortLtv": 0.75,
          "longLtv": 0.75,
          "cashbackMode": "cash",
          "cashOutEnabled": true,
          "degenEnabled": false,
          "degenMode": "x1",
          "customRecyclePct": 0
        },
        "routing": "cash",
        "targetReturn": 408.3333333333333
      }
    },
    "objectiveAnalysis": null
  },
  {
    "comparisonMode": "base",
    "objective": "bearish",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 10000,
        "longAllocation": 0,
        "longMode": "2x",
        "shortMode": "2.5x-looped",
        "shortLtv": 0.75,
        "longLtv": 0.5,
        "cashbackMode": "cash",
        "cashOutEnabled": false,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "upside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": null,
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 900,
            "regionsAvailable": 1818,
            "regionsRetained": 918,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 900,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": null
  },
  {
    "comparisonMode": "base",
    "objective": "spotParity",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 10000,
        "longAllocation": 0.28,
        "longMode": "2.5x-looped",
        "shortMode": "2.5x-cashback",
        "shortLtv": 0.75,
        "longLtv": 0.75,
        "cashbackMode": "spot",
        "cashOutEnabled": true,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": {
        "kind": "spot",
        "targetPercent": 50,
        "targetValue": 1.5,
        "achievedValue": 1.5,
        "shortfall": 0,
        "reached": true
      },
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 900,
            "regionsAvailable": 1818,
            "regionsRetained": 918,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 900,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": {
      "kind": "spot",
      "target": {
        "v4Return": 50,
        "benchmarkReturn": 50,
        "parityMargin": 0
      },
      "v4MaxDrawdown": -27.997200000000007,
      "spotMaxDrawdown": -99,
      "protectionGained": 71.0028,
      "analysisMinMove": -99,
      "analysisMaxMove": 200
    }
  },
  {
    "comparisonMode": "base",
    "objective": "benchmarkDominance",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 10000,
        "longAllocation": 0.5,
        "longMode": "2.5x-looped",
        "shortMode": "2x",
        "shortLtv": 0.5,
        "longLtv": 0.75,
        "cashbackMode": "cash",
        "cashOutEnabled": false,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": null,
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 900,
            "regionsAvailable": 1818,
            "regionsRetained": 918,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 900,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": {
      "kind": "dominance",
      "result": {
        "benchmark": "spot",
        "requestedMinMove": -99,
        "requestedMaxMove": 200,
        "effectiveMinMove": -99,
        "effectiveMaxMove": 200,
        "worstEdgePts": 0,
        "worstMove": 0,
        "aheadPercent": 99.66666666666667,
        "averageEdgePts": 90.23136566916253,
        "maxDrawdown": -0.49995
      }
    }
  },
  {
    "comparisonMode": "lending",
    "objective": "bullish",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 25000,
        "longAllocation": 0.5,
        "longMode": "2.5x-looped",
        "shortMode": "2.5x-cashback",
        "shortLtv": 0.75,
        "longLtv": 0.75,
        "cashbackMode": "spot",
        "cashOutEnabled": true,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": null,
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 900,
            "regionsAvailable": 1818,
            "regionsRetained": 918,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 900,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": {
      "targetPercent": 200,
      "selected": {
        "config": {
          "deposit": 25000,
          "longAllocation": 0.5,
          "longMode": "2.5x-looped",
          "shortMode": "2.5x-cashback",
          "shortLtv": 0.75,
          "longLtv": 0.75,
          "cashbackMode": "spot",
          "cashOutEnabled": true,
          "degenEnabled": false,
          "degenMode": "x1",
          "customRecyclePct": 0
        },
        "routing": "spot",
        "targetReturn": 458.33333333333337
      },
      "alternative": {
        "config": {
          "deposit": 25000,
          "longAllocation": 0.5,
          "longMode": "2.5x-looped",
          "shortMode": "2.5x-cashback",
          "shortLtv": 0.75,
          "longLtv": 0.75,
          "cashbackMode": "cash",
          "cashOutEnabled": true,
          "degenEnabled": false,
          "degenMode": "x1",
          "customRecyclePct": 0
        },
        "routing": "cash",
        "targetReturn": 408.3333333333333
      }
    },
    "objectiveAnalysis": null
  },
  {
    "comparisonMode": "lending",
    "objective": "bearish",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 25000,
        "longAllocation": 0,
        "longMode": "2x",
        "shortMode": "2.5x-looped",
        "shortLtv": 0.75,
        "longLtv": 0.5,
        "cashbackMode": "cash",
        "cashOutEnabled": false,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "upside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": null,
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 900,
            "regionsAvailable": 1818,
            "regionsRetained": 918,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 900,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": null
  },
  {
    "comparisonMode": "lending",
    "objective": "spotParity",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 25000,
        "longAllocation": 0.28,
        "longMode": "2.5x-looped",
        "shortMode": "2.5x-cashback",
        "shortLtv": 0.75,
        "longLtv": 0.75,
        "cashbackMode": "spot",
        "cashOutEnabled": true,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": {
        "kind": "spot",
        "targetPercent": 50,
        "targetValue": 1.5,
        "achievedValue": 1.5,
        "shortfall": 0,
        "reached": true
      },
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 900,
            "regionsAvailable": 1818,
            "regionsRetained": 918,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 900,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": {
      "kind": "spot",
      "target": {
        "v4Return": 50,
        "benchmarkReturn": 50,
        "parityMargin": 0
      },
      "v4MaxDrawdown": -27.997200000000007,
      "spotMaxDrawdown": -99,
      "protectionGained": 71.0028,
      "analysisMinMove": -99,
      "analysisMaxMove": 200
    }
  },
  {
    "comparisonMode": "lending",
    "objective": "debtParity",
    "outcome": {
      "status": "best-effort",
      "config": {
        "deposit": 25000,
        "longAllocation": 0.5,
        "longMode": "2.5x-looped",
        "shortMode": "2.5x-cashback",
        "shortLtv": 0.75,
        "longLtv": 0.75,
        "cashbackMode": "spot",
        "cashOutEnabled": true,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": {
        "targetPercent": 50,
        "debtValue": 45000,
        "v4Value": 43229.166666666664,
        "secured": false
      },
      "perpParity": null,
      "parity": {
        "kind": "lending",
        "targetPercent": 50,
        "targetValue": 45000,
        "achievedValue": 43229.166666666664,
        "shortfall": 1770.8333333333358,
        "reached": false
      },
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 900,
            "regionsAvailable": 1818,
            "regionsRetained": 918,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 900,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": {
      "kind": "lending",
      "target": {
        "v4Return": 72.91666666666666,
        "benchmarkReturn": 80,
        "parityMargin": -7.083333333333343
      },
      "liquidation": {
        "assetMove": -55.88235294117647,
        "assetPrice": 882.3529411764706,
        "v4Return": -29.5573817762399,
        "v4Value": 17610.654555940026
      }
    }
  },
  {
    "comparisonMode": "lending",
    "objective": "benchmarkDominance",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 25000,
        "longAllocation": 0.5,
        "longMode": "2.5x-looped",
        "shortMode": "2.5x-cashback",
        "shortLtv": 0.75,
        "longLtv": 0.75,
        "cashbackMode": "spot",
        "cashOutEnabled": true,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": null,
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 900,
            "regionsAvailable": 1818,
            "regionsRetained": 918,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 900,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": {
      "kind": "dominance",
      "result": {
        "benchmark": "lending",
        "requestedMinMove": -99,
        "requestedMaxMove": 200,
        "effectiveMinMove": -55.88235294117647,
        "effectiveMaxMove": 200,
        "worstEdgePts": -8.23764818558641,
        "worstMove": 36.013711024179834,
        "aheadPercent": 70.93023255813954,
        "averageEdgePts": 30.95483893658133,
        "maxDrawdown": -0.49995
      }
    }
  },
  {
    "comparisonMode": "perp",
    "objective": "bullish",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 17500,
        "longAllocation": 0.5,
        "longMode": "2.5x-looped",
        "shortMode": "2.5x-cashback",
        "shortLtv": 0.75,
        "longLtv": 0.75,
        "cashbackMode": "spot",
        "cashOutEnabled": true,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": null,
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 900,
            "regionsAvailable": 1818,
            "regionsRetained": 918,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 900,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": {
      "targetPercent": 200,
      "selected": {
        "config": {
          "deposit": 17500,
          "longAllocation": 0.5,
          "longMode": "2.5x-looped",
          "shortMode": "2.5x-cashback",
          "shortLtv": 0.75,
          "longLtv": 0.75,
          "cashbackMode": "spot",
          "cashOutEnabled": true,
          "degenEnabled": false,
          "degenMode": "x1",
          "customRecyclePct": 0
        },
        "routing": "spot",
        "targetReturn": 458.33333333333337
      },
      "alternative": {
        "config": {
          "deposit": 17500,
          "longAllocation": 0.5,
          "longMode": "2.5x-looped",
          "shortMode": "2.5x-cashback",
          "shortLtv": 0.75,
          "longLtv": 0.75,
          "cashbackMode": "cash",
          "cashOutEnabled": true,
          "degenEnabled": false,
          "degenMode": "x1",
          "customRecyclePct": 0
        },
        "routing": "cash",
        "targetReturn": 408.3333333333333
      }
    },
    "objectiveAnalysis": null
  },
  {
    "comparisonMode": "perp",
    "objective": "bearish",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 17500,
        "longAllocation": 0,
        "longMode": "2x",
        "shortMode": "2.5x-looped",
        "shortLtv": 0.75,
        "longLtv": 0.5,
        "cashbackMode": "cash",
        "cashOutEnabled": false,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "upside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": null,
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 900,
            "regionsAvailable": 1818,
            "regionsRetained": 918,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 900,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": null
  },
  {
    "comparisonMode": "perp",
    "objective": "spotParity",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 17500,
        "longAllocation": 0.28,
        "longMode": "2.5x-looped",
        "shortMode": "2.5x-cashback",
        "shortLtv": 0.75,
        "longLtv": 0.75,
        "cashbackMode": "spot",
        "cashOutEnabled": true,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": {
        "kind": "spot",
        "targetPercent": 50,
        "targetValue": 1.5,
        "achievedValue": 1.5,
        "shortfall": 0,
        "reached": true
      },
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 900,
            "regionsAvailable": 1818,
            "regionsRetained": 918,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 900,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": {
      "kind": "spot",
      "target": {
        "v4Return": 50,
        "benchmarkReturn": 50,
        "parityMargin": 0
      },
      "v4MaxDrawdown": -27.997200000000007,
      "spotMaxDrawdown": -99,
      "protectionGained": 71.0028,
      "analysisMinMove": -99,
      "analysisMaxMove": 200
    }
  },
  {
    "comparisonMode": "perp",
    "objective": "perpParity",
    "outcome": {
      "status": "best-effort",
      "config": {
        "deposit": 17500,
        "longAllocation": 0.5,
        "longMode": "2.5x-looped",
        "shortMode": "2.5x-cashback",
        "shortLtv": 0.75,
        "longLtv": 0.75,
        "cashbackMode": "spot",
        "cashOutEnabled": true,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": {
        "targetPercent": 50,
        "perpValue": 32500,
        "v4Value": 30260.416666666664,
        "secured": false
      },
      "parity": {
        "kind": "perp",
        "targetPercent": 50,
        "targetValue": 32500,
        "achievedValue": 30260.416666666664,
        "shortfall": 2239.5833333333358,
        "reached": false
      },
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 900,
            "regionsAvailable": 1818,
            "regionsRetained": 918,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 900,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": {
      "kind": "perp",
      "target": {
        "v4Return": 72.91666666666666,
        "benchmarkReturn": 85.71428571428572,
        "parityMargin": -12.797619047619065
      },
      "liquidation": {
        "assetMove": -40,
        "assetPrice": 1200,
        "v4Return": -30.33333333333332,
        "v4Value": 12191.666666666668
      }
    }
  },
  {
    "comparisonMode": "perp",
    "objective": "benchmarkDominance",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 17500,
        "longAllocation": 0.5,
        "longMode": "2.5x-looped",
        "shortMode": "2.5x-cashback",
        "shortLtv": 0.75,
        "longLtv": 0.75,
        "cashbackMode": "spot",
        "cashOutEnabled": true,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": null,
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 900,
            "regionsAvailable": 1818,
            "regionsRetained": 918,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 900,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": {
      "kind": "dominance",
      "result": {
        "benchmark": "perp",
        "requestedMinMove": -99,
        "requestedMaxMove": 200,
        "effectiveMinMove": -40,
        "effectiveMaxMove": 200,
        "worstEdgePts": -12.904362303767215,
        "worstMove": 45.704474749269906,
        "aheadPercent": 60.99585062240664,
        "averageEdgePts": 20.85652184069506,
        "maxDrawdown": -0.49995
      }
    }
  }
];
