// Generated by npm run generate:presets. Do not edit by hand.
import type { DefaultOptimisationPreset } from "./defaultOptimisationPresets";

export const GENERATED_DEFAULT_OPTIMISATION_PRESET_MODEL_VERSION = "v4-discrete-products-exhaustive-2026-08-19-short-cashback-inverse-square-1";
export const GENERATED_DEFAULT_OPTIMISATION_PRESETS: DefaultOptimisationPreset[] = [
  {
    "comparisonMode": "base",
    "objective": "bullish",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 10000,
        "longAllocation": 0.5,
        "longMode": "2.5x-looped",
        "shortMode": "2x",
        "shortLtv": 0.5,
        "longLtv": 0.75,
        "cashbackMode": "cash",
        "cashOutEnabled": false,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": null,
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 1164,
            "regionsAvailable": 1818,
            "regionsRetained": 654,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 1164,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": null
  },
  {
    "comparisonMode": "base",
    "objective": "bearish",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 10000,
        "longAllocation": 0.44,
        "longMode": "2.5x-cashback",
        "shortMode": "2.5x-cashback",
        "shortLtv": 0.75,
        "longLtv": 0.75,
        "cashbackMode": "cash",
        "cashOutEnabled": true,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "upside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": null,
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 1164,
            "regionsAvailable": 1818,
            "regionsRetained": 654,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 1164,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": null
  },
  {
    "comparisonMode": "base",
    "objective": "spotParity",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 10000,
        "longAllocation": 0.36,
        "longMode": "2.5x-looped",
        "shortMode": "2x",
        "shortLtv": 0.5,
        "longLtv": 0.75,
        "cashbackMode": "cash",
        "cashOutEnabled": false,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": {
        "kind": "spot",
        "targetPercent": 50,
        "targetValue": 1.5,
        "achievedValue": 1.5033333333333332,
        "shortfall": 0,
        "reached": true
      },
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 1164,
            "regionsAvailable": 1818,
            "regionsRetained": 654,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 1164,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": {
      "kind": "spot",
      "target": {
        "v4Return": 50.33333333333332,
        "benchmarkReturn": 50,
        "parityMargin": 0.3333333333333215
      },
      "v4MaxDrawdown": -35.9964,
      "spotMaxDrawdown": -99,
      "protectionGained": 63.0036,
      "analysisMinMove": -99,
      "analysisMaxMove": 200
    }
  },
  {
    "comparisonMode": "base",
    "objective": "benchmarkDominance",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 10000,
        "longAllocation": 0.5,
        "longMode": "2.5x-looped",
        "shortMode": "2x",
        "shortLtv": 0.5,
        "longLtv": 0.75,
        "cashbackMode": "cash",
        "cashOutEnabled": false,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": null,
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 1164,
            "regionsAvailable": 1818,
            "regionsRetained": 654,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 1164,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": {
      "kind": "dominance",
      "result": {
        "benchmark": "spot",
        "requestedMinMove": -99,
        "requestedMaxMove": 200,
        "effectiveMinMove": -99,
        "effectiveMaxMove": 200,
        "worstEdgePts": 0,
        "worstMove": 0,
        "aheadPercent": 99.66666666666667,
        "averageEdgePts": 90.23136566916253,
        "maxDrawdown": -0.49995
      }
    }
  },
  {
    "comparisonMode": "lending",
    "objective": "bullish",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 25000,
        "longAllocation": 0.5,
        "longMode": "2.5x-looped",
        "shortMode": "2x",
        "shortLtv": 0.5,
        "longLtv": 0.75,
        "cashbackMode": "cash",
        "cashOutEnabled": false,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": null,
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 1164,
            "regionsAvailable": 1818,
            "regionsRetained": 654,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 1164,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": null
  },
  {
    "comparisonMode": "lending",
    "objective": "bearish",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 25000,
        "longAllocation": 0.44,
        "longMode": "2.5x-cashback",
        "shortMode": "2.5x-cashback",
        "shortLtv": 0.75,
        "longLtv": 0.75,
        "cashbackMode": "cash",
        "cashOutEnabled": true,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "upside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": null,
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 1164,
            "regionsAvailable": 1818,
            "regionsRetained": 654,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 1164,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": null
  },
  {
    "comparisonMode": "lending",
    "objective": "spotParity",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 25000,
        "longAllocation": 0.36,
        "longMode": "2.5x-looped",
        "shortMode": "2x",
        "shortLtv": 0.5,
        "longLtv": 0.75,
        "cashbackMode": "cash",
        "cashOutEnabled": false,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": {
        "kind": "spot",
        "targetPercent": 50,
        "targetValue": 1.5,
        "achievedValue": 1.5033333333333332,
        "shortfall": 0,
        "reached": true
      },
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 1164,
            "regionsAvailable": 1818,
            "regionsRetained": 654,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 1164,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": {
      "kind": "spot",
      "target": {
        "v4Return": 50.33333333333332,
        "benchmarkReturn": 50,
        "parityMargin": 0.3333333333333215
      },
      "v4MaxDrawdown": -35.9964,
      "spotMaxDrawdown": -99,
      "protectionGained": 63.0036,
      "analysisMinMove": -99,
      "analysisMaxMove": 200
    }
  },
  {
    "comparisonMode": "lending",
    "objective": "debtParity",
    "outcome": {
      "status": "best-effort",
      "config": {
        "deposit": 25000,
        "longAllocation": 0.5,
        "longMode": "2.5x-looped",
        "shortMode": "2x",
        "shortLtv": 0.5,
        "longLtv": 0.75,
        "cashbackMode": "cash",
        "cashOutEnabled": false,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": {
        "targetPercent": 50,
        "debtValue": 45000,
        "v4Value": 41666.666666666664,
        "secured": false
      },
      "perpParity": null,
      "parity": {
        "kind": "lending",
        "targetPercent": 50,
        "targetValue": 45000,
        "achievedValue": 41666.666666666664,
        "shortfall": 3333.3333333333358,
        "reached": false
      },
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 1164,
            "regionsAvailable": 1818,
            "regionsRetained": 654,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 1164,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": {
      "kind": "lending",
      "target": {
        "v4Return": 66.66666666666666,
        "benchmarkReturn": 80,
        "parityMargin": -13.333333333333343
      },
      "liquidation": {
        "assetMove": -55.88235294117647,
        "assetPrice": 882.3529411764706,
        "v4Return": -22.572087658592842,
        "v4Value": 19356.978085351788
      }
    }
  },
  {
    "comparisonMode": "lending",
    "objective": "benchmarkDominance",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 25000,
        "longAllocation": 0.5,
        "longMode": "2.5x-looped",
        "shortMode": "2x",
        "shortLtv": 0.5,
        "longLtv": 0.75,
        "cashbackMode": "cash",
        "cashOutEnabled": false,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": null,
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 1164,
            "regionsAvailable": 1818,
            "regionsRetained": 654,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 1164,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": {
      "kind": "dominance",
      "result": {
        "benchmark": "lending",
        "requestedMinMove": -99,
        "requestedMaxMove": 200,
        "effectiveMinMove": -55.88235294117647,
        "effectiveMaxMove": 200,
        "worstEdgePts": -13.398998547854802,
        "worstMove": 46.62802796854767,
        "aheadPercent": 62.4031007751938,
        "averageEdgePts": 21.975130774246633,
        "maxDrawdown": -0.49995
      }
    }
  },
  {
    "comparisonMode": "perp",
    "objective": "bullish",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 17500,
        "longAllocation": 0.5,
        "longMode": "2.5x-looped",
        "shortMode": "2x",
        "shortLtv": 0.5,
        "longLtv": 0.75,
        "cashbackMode": "cash",
        "cashOutEnabled": false,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": null,
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 1164,
            "regionsAvailable": 1818,
            "regionsRetained": 654,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 1164,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": null
  },
  {
    "comparisonMode": "perp",
    "objective": "bearish",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 17500,
        "longAllocation": 0.44,
        "longMode": "2.5x-cashback",
        "shortMode": "2.5x-cashback",
        "shortLtv": 0.75,
        "longLtv": 0.75,
        "cashbackMode": "cash",
        "cashOutEnabled": true,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "upside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": null,
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 1164,
            "regionsAvailable": 1818,
            "regionsRetained": 654,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 1164,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": null
  },
  {
    "comparisonMode": "perp",
    "objective": "spotParity",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 17500,
        "longAllocation": 0.36,
        "longMode": "2.5x-looped",
        "shortMode": "2x",
        "shortLtv": 0.5,
        "longLtv": 0.75,
        "cashbackMode": "cash",
        "cashOutEnabled": false,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": {
        "kind": "spot",
        "targetPercent": 50,
        "targetValue": 1.5,
        "achievedValue": 1.5033333333333332,
        "shortfall": 0,
        "reached": true
      },
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 1164,
            "regionsAvailable": 1818,
            "regionsRetained": 654,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 1164,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": {
      "kind": "spot",
      "target": {
        "v4Return": 50.33333333333332,
        "benchmarkReturn": 50,
        "parityMargin": 0.3333333333333215
      },
      "v4MaxDrawdown": -35.9964,
      "spotMaxDrawdown": -99,
      "protectionGained": 63.0036,
      "analysisMinMove": -99,
      "analysisMaxMove": 200
    }
  },
  {
    "comparisonMode": "perp",
    "objective": "perpParity",
    "outcome": {
      "status": "best-effort",
      "config": {
        "deposit": 17500,
        "longAllocation": 0.5,
        "longMode": "2.5x-looped",
        "shortMode": "2x",
        "shortLtv": 0.5,
        "longLtv": 0.75,
        "cashbackMode": "cash",
        "cashOutEnabled": false,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": {
        "targetPercent": 50,
        "perpValue": 32500,
        "v4Value": 29166.666666666664,
        "secured": false
      },
      "parity": {
        "kind": "perp",
        "targetPercent": 50,
        "targetValue": 32500,
        "achievedValue": 29166.666666666664,
        "shortfall": 3333.3333333333358,
        "reached": false
      },
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 1164,
            "regionsAvailable": 1818,
            "regionsRetained": 654,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 1164,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": {
      "kind": "perp",
      "target": {
        "v4Return": 66.66666666666666,
        "benchmarkReturn": 85.71428571428572,
        "parityMargin": -19.047619047619065
      },
      "liquidation": {
        "assetMove": -40,
        "assetPrice": 1200,
        "v4Return": -25.333333333333343,
        "v4Value": 13066.666666666666
      }
    }
  },
  {
    "comparisonMode": "perp",
    "objective": "benchmarkDominance",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 17500,
        "longAllocation": 0.5,
        "longMode": "2.5x-looped",
        "shortMode": "2x",
        "shortLtv": 0.5,
        "longLtv": 0.75,
        "cashbackMode": "cash",
        "cashOutEnabled": false,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": null,
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 1164,
            "regionsAvailable": 1818,
            "regionsRetained": 654,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 1164,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": {
      "kind": "dominance",
      "result": {
        "benchmark": "perp",
        "requestedMinMove": -99,
        "requestedMaxMove": 200,
        "effectiveMinMove": -40,
        "effectiveMaxMove": 200,
        "worstEdgePts": -19.29653363629418,
        "worstMove": 56.620218415911836,
        "aheadPercent": 51.45228215767634,
        "averageEdgePts": 10.856521840695061,
        "maxDrawdown": -0.49995
      }
    }
  }
];
