// Generated by npm run generate:presets. Do not edit by hand.
import type { DefaultOptimisationPreset } from "./defaultOptimisationPresets";

export const GENERATED_DEFAULT_OPTIMISATION_PRESET_MODEL_VERSION = "v4-discrete-products-exhaustive-2026-08-19-short-cashback-inverse-square-1";
export const GENERATED_DEFAULT_OPTIMISATION_PRESETS: DefaultOptimisationPreset[] = [
  {
    "comparisonMode": "base",
    "objective": "bullish",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 10000,
        "longAllocation": 0.5,
        "longMode": "2.5x-looped",
        "shortMode": "2.5x-cashback",
        "shortLtv": 0.75,
        "longLtv": 0.75,
        "cashbackMode": "spot",
        "cashOutEnabled": true,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": null,
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 900,
            "regionsAvailable": 1818,
            "regionsRetained": 918,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 900,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": {
      "targetPercent": 200,
      "selected": {
        "config": {
          "deposit": 10000,
          "longAllocation": 0.5,
          "longMode": "2.5x-looped",
          "shortMode": "2.5x-cashback",
          "shortLtv": 0.75,
          "longLtv": 0.75,
          "cashbackMode": "spot",
          "cashOutEnabled": true,
          "degenEnabled": false,
          "degenMode": "x1",
          "customRecyclePct": 0
        },
        "routing": "spot",
        "targetReturn": 477.77777777777777
      },
      "alternative": {
        "config": {
          "deposit": 10000,
          "longAllocation": 0.5,
          "longMode": "2.5x-looped",
          "shortMode": "2.5x-cashback",
          "shortLtv": 0.75,
          "longLtv": 0.75,
          "cashbackMode": "cash",
          "cashOutEnabled": true,
          "degenEnabled": false,
          "degenMode": "x1",
          "customRecyclePct": 0
        },
        "routing": "cash",
        "targetReturn": 427.77777777777777
      }
    },
    "objectiveAnalysis": null
  },
  {
    "comparisonMode": "base",
    "objective": "bearish",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 10000,
        "longAllocation": 0,
        "longMode": "2x",
        "shortMode": "2.5x-cashback",
        "shortLtv": 0.75,
        "longLtv": 0.5,
        "cashbackMode": "cash",
        "cashOutEnabled": true,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "upside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": null,
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 900,
            "regionsAvailable": 1818,
            "regionsRetained": 918,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 900,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": null
  },
  {
    "comparisonMode": "base",
    "objective": "spotParity",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 10000,
        "longAllocation": 0.28,
        "longMode": "2.5x-looped",
        "shortMode": "2.5x-cashback",
        "shortLtv": 0.75,
        "longLtv": 0.75,
        "cashbackMode": "spot",
        "cashOutEnabled": true,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": {
        "kind": "spot",
        "targetPercent": 50,
        "targetValue": 1.5,
        "achievedValue": 1.5100000000000002,
        "shortfall": 0,
        "reached": true
      },
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 900,
            "regionsAvailable": 1818,
            "regionsRetained": 918,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 900,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": {
      "kind": "spot",
      "target": {
        "v4Return": 51.00000000000002,
        "benchmarkReturn": 50,
        "parityMargin": 1.0000000000000213
      },
      "v4MaxDrawdown": -27.997200000000007,
      "spotMaxDrawdown": -99,
      "protectionGained": 71.0028,
      "analysisMinMove": -99,
      "analysisMaxMove": 200
    }
  },
  {
    "comparisonMode": "base",
    "objective": "benchmarkDominance",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 10000,
        "longAllocation": 0.5,
        "longMode": "2.5x-looped",
        "shortMode": "2.5x-cashback",
        "shortLtv": 0.75,
        "longLtv": 0.75,
        "cashbackMode": "spot",
        "cashOutEnabled": true,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": null,
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 900,
            "regionsAvailable": 1818,
            "regionsRetained": 918,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 900,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": {
      "kind": "dominance",
      "result": {
        "benchmark": "spot",
        "requestedMinMove": -99,
        "requestedMaxMove": 200,
        "effectiveMinMove": -99,
        "effectiveMaxMove": 200,
        "worstEdgePts": 0,
        "worstMove": 0,
        "aheadPercent": 99.66666666666667,
        "averageEdgePts": 1418.5060690813505,
        "maxDrawdown": -0.49995
      }
    }
  },
  {
    "comparisonMode": "lending",
    "objective": "bullish",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 25000,
        "longAllocation": 0.5,
        "longMode": "2.5x-looped",
        "shortMode": "2.5x-cashback",
        "shortLtv": 0.75,
        "longLtv": 0.75,
        "cashbackMode": "spot",
        "cashOutEnabled": true,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": null,
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 900,
            "regionsAvailable": 1818,
            "regionsRetained": 918,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 900,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": {
      "targetPercent": 200,
      "selected": {
        "config": {
          "deposit": 25000,
          "longAllocation": 0.5,
          "longMode": "2.5x-looped",
          "shortMode": "2.5x-cashback",
          "shortLtv": 0.75,
          "longLtv": 0.75,
          "cashbackMode": "spot",
          "cashOutEnabled": true,
          "degenEnabled": false,
          "degenMode": "x1",
          "customRecyclePct": 0
        },
        "routing": "spot",
        "targetReturn": 477.77777777777777
      },
      "alternative": {
        "config": {
          "deposit": 25000,
          "longAllocation": 0.5,
          "longMode": "2.5x-looped",
          "shortMode": "2.5x-cashback",
          "shortLtv": 0.75,
          "longLtv": 0.75,
          "cashbackMode": "cash",
          "cashOutEnabled": true,
          "degenEnabled": false,
          "degenMode": "x1",
          "customRecyclePct": 0
        },
        "routing": "cash",
        "targetReturn": 427.77777777777777
      }
    },
    "objectiveAnalysis": null
  },
  {
    "comparisonMode": "lending",
    "objective": "bearish",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 25000,
        "longAllocation": 0,
        "longMode": "2x",
        "shortMode": "2.5x-cashback",
        "shortLtv": 0.75,
        "longLtv": 0.5,
        "cashbackMode": "cash",
        "cashOutEnabled": true,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "upside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": null,
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 900,
            "regionsAvailable": 1818,
            "regionsRetained": 918,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 900,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": null
  },
  {
    "comparisonMode": "lending",
    "objective": "spotParity",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 25000,
        "longAllocation": 0.28,
        "longMode": "2.5x-looped",
        "shortMode": "2.5x-cashback",
        "shortLtv": 0.75,
        "longLtv": 0.75,
        "cashbackMode": "spot",
        "cashOutEnabled": true,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": {
        "kind": "spot",
        "targetPercent": 50,
        "targetValue": 1.5,
        "achievedValue": 1.5100000000000002,
        "shortfall": 0,
        "reached": true
      },
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 900,
            "regionsAvailable": 1818,
            "regionsRetained": 918,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 900,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": {
      "kind": "spot",
      "target": {
        "v4Return": 51.00000000000002,
        "benchmarkReturn": 50,
        "parityMargin": 1.0000000000000213
      },
      "v4MaxDrawdown": -27.997200000000007,
      "spotMaxDrawdown": -99,
      "protectionGained": 71.0028,
      "analysisMinMove": -99,
      "analysisMaxMove": 200
    }
  },
  {
    "comparisonMode": "lending",
    "objective": "debtParity",
    "outcome": {
      "status": "best-effort",
      "config": {
        "deposit": 25000,
        "longAllocation": 0.5,
        "longMode": "2.5x-looped",
        "shortMode": "2.5x-cashback",
        "shortLtv": 0.75,
        "longLtv": 0.75,
        "cashbackMode": "spot",
        "cashOutEnabled": true,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": {
        "targetPercent": 50,
        "debtValue": 45000,
        "v4Value": 43402.77777777778,
        "secured": false
      },
      "perpParity": null,
      "parity": {
        "kind": "lending",
        "targetPercent": 50,
        "targetValue": 45000,
        "achievedValue": 43402.77777777778,
        "shortfall": 1597.222222222219,
        "reached": false
      },
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 900,
            "regionsAvailable": 1818,
            "regionsRetained": 918,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 900,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": {
      "kind": "lending",
      "target": {
        "v4Return": 73.61111111111111,
        "benchmarkReturn": 80,
        "parityMargin": -6.388888888888886
      },
      "liquidation": {
        "assetMove": -55.88235294117647,
        "assetPrice": 882.3529411764706,
        "v4Return": 35.23510188389083,
        "v4Value": 33808.77547097271
      }
    }
  },
  {
    "comparisonMode": "lending",
    "objective": "benchmarkDominance",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 25000,
        "longAllocation": 0.5,
        "longMode": "2.5x-looped",
        "shortMode": "2.5x-cashback",
        "shortLtv": 0.75,
        "longLtv": 0.75,
        "cashbackMode": "spot",
        "cashOutEnabled": true,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": null,
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 900,
            "regionsAvailable": 1818,
            "regionsRetained": 918,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 900,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": {
      "kind": "dominance",
      "result": {
        "benchmark": "lending",
        "requestedMinMove": -99,
        "requestedMaxMove": 200,
        "effectiveMinMove": -55.88235294117647,
        "effectiveMaxMove": 200,
        "worstEdgePts": -8.73220137035342,
        "worstMove": 31.825752459533117,
        "aheadPercent": 73.25581395348837,
        "averageEdgePts": 40.220836879636,
        "maxDrawdown": -0.49995
      }
    }
  },
  {
    "comparisonMode": "perp",
    "objective": "bullish",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 17500,
        "longAllocation": 0.5,
        "longMode": "2.5x-looped",
        "shortMode": "2.5x-cashback",
        "shortLtv": 0.75,
        "longLtv": 0.75,
        "cashbackMode": "spot",
        "cashOutEnabled": true,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": null,
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 900,
            "regionsAvailable": 1818,
            "regionsRetained": 918,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 900,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": {
      "targetPercent": 200,
      "selected": {
        "config": {
          "deposit": 17500,
          "longAllocation": 0.5,
          "longMode": "2.5x-looped",
          "shortMode": "2.5x-cashback",
          "shortLtv": 0.75,
          "longLtv": 0.75,
          "cashbackMode": "spot",
          "cashOutEnabled": true,
          "degenEnabled": false,
          "degenMode": "x1",
          "customRecyclePct": 0
        },
        "routing": "spot",
        "targetReturn": 477.77777777777777
      },
      "alternative": {
        "config": {
          "deposit": 17500,
          "longAllocation": 0.5,
          "longMode": "2.5x-looped",
          "shortMode": "2.5x-cashback",
          "shortLtv": 0.75,
          "longLtv": 0.75,
          "cashbackMode": "cash",
          "cashOutEnabled": true,
          "degenEnabled": false,
          "degenMode": "x1",
          "customRecyclePct": 0
        },
        "routing": "cash",
        "targetReturn": 427.77777777777777
      }
    },
    "objectiveAnalysis": null
  },
  {
    "comparisonMode": "perp",
    "objective": "bearish",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 17500,
        "longAllocation": 0,
        "longMode": "2x",
        "shortMode": "2.5x-cashback",
        "shortLtv": 0.75,
        "longLtv": 0.5,
        "cashbackMode": "cash",
        "cashOutEnabled": true,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "upside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": null,
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 900,
            "regionsAvailable": 1818,
            "regionsRetained": 918,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 900,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": null
  },
  {
    "comparisonMode": "perp",
    "objective": "spotParity",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 17500,
        "longAllocation": 0.28,
        "longMode": "2.5x-looped",
        "shortMode": "2.5x-cashback",
        "shortLtv": 0.75,
        "longLtv": 0.75,
        "cashbackMode": "spot",
        "cashOutEnabled": true,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": {
        "kind": "spot",
        "targetPercent": 50,
        "targetValue": 1.5,
        "achievedValue": 1.5100000000000002,
        "shortfall": 0,
        "reached": true
      },
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 900,
            "regionsAvailable": 1818,
            "regionsRetained": 918,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 900,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": {
      "kind": "spot",
      "target": {
        "v4Return": 51.00000000000002,
        "benchmarkReturn": 50,
        "parityMargin": 1.0000000000000213
      },
      "v4MaxDrawdown": -27.997200000000007,
      "spotMaxDrawdown": -99,
      "protectionGained": 71.0028,
      "analysisMinMove": -99,
      "analysisMaxMove": 200
    }
  },
  {
    "comparisonMode": "perp",
    "objective": "perpParity",
    "outcome": {
      "status": "best-effort",
      "config": {
        "deposit": 17500,
        "longAllocation": 0.5,
        "longMode": "2.5x-looped",
        "shortMode": "2.5x-cashback",
        "shortLtv": 0.75,
        "longLtv": 0.75,
        "cashbackMode": "spot",
        "cashOutEnabled": true,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": {
        "targetPercent": 50,
        "perpValue": 32500,
        "v4Value": 30381.944444444445,
        "secured": false
      },
      "parity": {
        "kind": "perp",
        "targetPercent": 50,
        "targetValue": 32500,
        "achievedValue": 30381.944444444445,
        "shortfall": 2118.0555555555547,
        "reached": false
      },
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 900,
            "regionsAvailable": 1818,
            "regionsRetained": 918,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 900,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": {
      "kind": "perp",
      "target": {
        "v4Return": 73.61111111111111,
        "benchmarkReturn": 85.71428571428572,
        "parityMargin": -12.103174603174608
      },
      "liquidation": {
        "assetMove": -40,
        "assetPrice": 1200,
        "v4Return": -7.55555555555556,
        "v4Value": 16177.777777777777
      }
    }
  },
  {
    "comparisonMode": "perp",
    "objective": "benchmarkDominance",
    "outcome": {
      "status": "optimal",
      "config": {
        "deposit": 17500,
        "longAllocation": 0.5,
        "longMode": "2.5x-looped",
        "shortMode": "2.5x-cashback",
        "shortLtv": 0.75,
        "longLtv": 0.75,
        "cashbackMode": "spot",
        "cashOutEnabled": true,
        "degenEnabled": false,
        "degenMode": "x1",
        "customRecyclePct": 0
      },
      "requestedMaxDrawdown": 0.5,
      "effectiveMaxDrawdown": 0.5,
      "drawdownRelaxed": false,
      "adverseDirection": "downside",
      "downsideBreakeven": null,
      "upsideBreakeven": null,
      "debtParity": null,
      "perpParity": null,
      "parity": null,
      "failure": null,
      "diagnostics": {
        "strategy": "exhaustive",
        "passes": [
          {
            "resolutionPercent": 1,
            "candidatesConsidered": 1818,
            "candidatesEvaluated": 1818,
            "candidatesRejected": 900,
            "regionsAvailable": 1818,
            "regionsRetained": 918,
            "regionsPruned": 0,
            "durationMs": 0
          }
        ],
        "candidatesConsidered": 1818,
        "candidatesEvaluated": 1818,
        "candidatesRejected": 900,
        "regionsPruned": 0,
        "durationMs": 0
      }
    },
    "productRoutingDecision": null,
    "objectiveAnalysis": {
      "kind": "dominance",
      "result": {
        "benchmark": "perp",
        "requestedMinMove": -99,
        "requestedMaxMove": 200,
        "effectiveMinMove": -40,
        "effectiveMaxMove": 200,
        "worstEdgePts": -12.816766368342613,
        "worstMove": 39.74864386243097,
        "aheadPercent": 64.73029045643153,
        "averageEdgePts": 28.039034109250554,
        "maxDrawdown": -0.49995
      }
    }
  }
];
